export type KnowledgeChunk = {
  id: string;
  title: string;
  source: string;
  text: string;
  kind?: "meeting-summary" | "meeting-transcript" | "strategy-chat" | "strategy-note" | "working-plan";
  folder?: string;
  session?: number;
  date?: string;
  aliases?: string[];
};

export const projectKnowledge: KnowledgeChunk[] = [
  {
    id: "project-purpose",
    title: "Project purpose",
    source: "Portal brief",
    aliases: ["project brain", "portal brief", "shared strategy room"],
    text: "This is a shared strategy room for the Canterbury pilot with Chris McBreen and Strategize. The purpose is to clarify the offer, shape the campaign, and map how qualified trade-business owners move from ad click to booked consult.",
  },
  {
    id: "client-reality",
    title: "Client reality and trust context",
    source: "Chris meeting summary",
    session: 1,
    aliases: ["meeting 1", "first meeting", "initial meeting"],
    text: "Chris is not buying a generic AI campaign. He is testing whether a serious creative and automation partner can protect his reputation with high-value trade clients. He had a poor prior experience and needs hands-on strategic consistency.",
  },
  {
    id: "business-model",
    title: "Strategize business model",
    source: "Chris meeting summary",
    session: 1,
    text: "Strategize sells high-ticket long-term strategy support, commonly around $2,000 to $3,000 per month, with long retention and relationships that can last around three years. Ideal clients are trade businesses with staff, not one-person operators.",
  },
  {
    id: "target-market",
    title: "Target market",
    source: "Chris meeting summary",
    session: 1,
    text: "The first market focus is Christchurch and Canterbury. The campaign should target trade-business owners, often age 35+, with multiple staff and enough turnover or operational complexity to make strategy support meaningful.",
  },
  {
    id: "lead-quality",
    title: "Lead quality principle",
    source: "Chris meeting summary",
    session: 1,
    text: "Lead quality matters more than lead volume. Telemarketing has produced qualified leads at about $66 each, so ads need to compete with or beat that quality benchmark. Volume without qualification is the failure mode.",
  },
  {
    id: "core-offer",
    title: "Core offer direction",
    source: "Offer strategy",
    aliases: ["offer direction", "benchmark", "gap analysis"],
    text: "The strongest offer is a benchmark-led profit leakage story: a free Business Gap Analysis or Benchmarking Report, with an implied value around $875, that helps owners see hidden losses such as $100,000 to $200,000 or more.",
  },
  {
    id: "creative-anchor",
    title: "Creative anchor",
    source: "Offer strategy",
    aliases: ["creative direction", "creative", "lead magnet"],
    text: "The creative should sell the size of the hidden gap. Chris already has a benchmark process that compares a business against its category and makes profit leakage tangible. The Meta creative job is to compress that moment without giving away proprietary numbers.",
  },
  {
    id: "offer-angles",
    title: "Six offer angles",
    source: "Campaign hypotheses",
    aliases: ["6 angles", "six angles", "offer options"],
    text: "The six offer angles are Productivity Gap, Margin and Pricing, Wage Leakage, Buying Group Savings, Subsidies and Grants, and Testimonial Proof. Subsidies and grants are considered weaker by Chris, but should remain in the option set for comparison.",
  },
  {
    id: "subsidies-grants",
    title: "Subsidies and grants angle",
    source: "Transcript note",
    aliases: ["wage subsidies", "grant subsidies", "regional business partner grants"],
    text: "Chris mentioned wage subsidies and regional business partner grants in a marketing context, but described them as weaker and a bit boring. They can be tested as an offer angle, but the benchmark gap analysis is the stronger strategic lead.",
  },
  {
    id: "system-map",
    title: "System map: lead to booked consult",
    source: "System walkthrough",
    aliases: ["lead to booked consult", "booked consult", "system"],
    text: "The system map moves from Traffic to Lead Capture to TradeAI CRM to AI Nurture to Qualification to Booked Consult to Human Handoff. Meta cold and warm campaigns and Google search can generate leads, which enter forms or a GHL funnel, then CRM tags, nurture, qualification, calendar booking, and human review.",
  },
  {
    id: "qualification",
    title: "Qualification requirements",
    source: "System walkthrough",
    aliases: ["qualify leads", "lead qualification", "disqualifiers"],
    text: "Qualification should capture pain, motivation, service fit, address, timezone, phone, and email. Disqualifiers include one-person businesses, no staff, insufficient turnover, duplicate existing contacts, or low-fit categories.",
  },
  {
    id: "ai-role",
    title: "Role of AI",
    source: "Chris meeting summary",
    session: 1,
    text: "AI is useful for speed-to-lead, follow-up, and qualification, but not the core acquisition idea. Automation is valuable after lead flow is proven. AI should protect the team from low-fit leads and improve conversion speed.",
  },
  {
    id: "working-stage",
    title: "Current project stage",
    source: "Working plan",
    kind: "working-plan",
    folder: "16 - working-plan",
    text: "The current stage is Offer Lock. Trust Reset is complete. Next stages are Creative Build, Funnel Build, AI Qualification, and Launch plus Optimise.",
  },
  {
    id: "chris-actions",
    title: "Chris action items",
    source: "Working plan",
    kind: "working-plan",
    folder: "16 - working-plan",
    text: "Chris action items are to send an anonymised benchmark or gap analysis sample, confirm compliant offer language, clarify ideal client filters, and identify testimonial or proof options.",
  },
  {
    id: "jesse-actions",
    title: "Jesse action items",
    source: "Working plan",
    kind: "working-plan",
    folder: "16 - working-plan",
    text: "Jesse action items are to draft first creative angles, shape the A/B campaign structure with the ads team, explore calculator or teaser funnel feasibility, and prepare a structured 90-minute workshop agenda.",
  },
  {
    id: "next-workshop",
    title: "Next workshop agenda",
    source: "Portal plan",
    kind: "working-plan",
    folder: "15 - working-notes",
    text: "The next workshop should confirm exact offer language, collect anonymised benchmark screenshots or a white-labelled sample report, choose the first three trade segments, define disqualifiers, and draft two video scripts.",
  },
  {
    id: "lead-gen-strategy-chat",
    title: "Lead gen strategy chat",
    source: "01 - transcripts / ChatGPT Strategize Chat from Feb to June26",
    kind: "strategy-chat",
    folder: "01 - transcripts",
    date: "2026-06-26",
    aliases: ["ads", "lead gen", "meta ads", "support available", "trades business support guide"],
    text: "This is a strategy chat about Meta lead generation for established NZ trades businesses, not a Chris meeting transcript. The core direction is practical, value-first lead magnets such as a trades systems map, business health scorecard, profit leak checklist, and a support guide framed without boring government-funding language. Messaging should focus on operational improvement, growth, and hidden opportunities for trade businesses with 5+ staff and meaningful turnover.",
  },
  {
    id: "meeting-1-transcript",
    title: "Meeting 1 transcript",
    source: "01 - transcripts / Meeting 01 - 2026-06-22 - Chris McBreen - Transcript",
    kind: "meeting-transcript",
    folder: "01 - transcripts",
    session: 1,
    date: "2026-06-22",
    aliases: ["meeting 1", "session 1", "first meeting", "transcript"],
    text: "The first meeting established the core commercial reality: Chris wants high-quality trade-business leads in Canterbury, not generic volume. He was unhappy with the earlier onboarding and wants a more strategic, hands-on process. Telemarketing currently produces qualified leads well, so Meta ads must compete on quality. The strongest offer emerging from the call was a benchmark or gap-analysis style hook showing missing profit, staff productivity gaps, and wasted spend.",
  },
  {
    id: "meeting-1-summary",
    title: "Meeting 1 summary",
    source: "01 - transcripts / Meeting 01 - 2026-06-23 - Chris McBreen - Summary",
    kind: "meeting-summary",
    folder: "01 - transcripts",
    session: 1,
    date: "2026-06-23",
    aliases: ["meeting 1 summary", "session 1 summary", "first meeting summary"],
    text: "Meeting 1 focused on trust reset, client-fit clarity, and the campaign offer. Chris needs a strategic, consistent approach after a poor onboarding experience. The commercial model is high-ticket long-term strategy support for trades businesses with roughly 5 to 20 staff, and low-fit one-man bands should be screened out. The strongest campaign hook is a free benchmarking or gap report that reveals hidden profit leakage, with creative centered on tangible red-flag losses in wages, productivity, and margin. Jesse's next steps were to draft creative angles, structure A/B campaign tests, and explore a simple calculator or teaser funnel, while Chris was to provide benchmark examples, proof assets, and clearer client filters.",
  },
  {
    id: "meeting-2-transcript",
    title: "Meeting 2 transcript",
    source: "01 - transcripts / Meeting 02 - 2026-06-27 - Chris McBreen - Transcript",
    kind: "meeting-transcript",
    folder: "01 - transcripts",
    session: 2,
    date: "2026-06-27",
    aliases: ["meeting 2", "session 2", "second meeting", "transcript"],
    text: "The second meeting sharpened the funnel around a profit leakage calculator and calculator-led landing page. Chris emphasized that trade categories have different margin profiles, so the tool should use a few simple inputs such as revenue, staff, and gross margin to show likely missing profit. The preferred path is ad to calculator to lead capture to qualification call to in-person consult, with Canterbury as the first test region and 2 to 4 ads plus retargeting. Qualification should capture revenue, staff size, whether they already have a coach, and location. Chris also wants human follow-up during business hours, AI after-hours, and no major CRM automation until the front-end campaign proves itself.",
  },
  {
    id: "meeting-2-summary",
    title: "Meeting 2 summary",
    source: "01 - transcripts / Meeting 02 - 2026-06-27 - Chris McBreen - Summary",
    kind: "meeting-summary",
    folder: "01 - transcripts",
    session: 2,
    date: "2026-06-27",
    aliases: ["meeting 2 summary", "session 2 summary", "second meeting summary"],
    text: "Meeting 2 locked the core direction around a value-first diagnostic funnel: ad to calculator to lead capture to qualification call to in-person consult. Chris validated the profit leakage calculator as the primary offer, with wage subsidy and buying group angles as secondary tests. The calculator should feel fast and simple, using a few inputs to estimate hidden profit loss and trigger curiosity. Qualification remains critical: revenue, staff size, existing coach, and location are the main filters, with a focus on multi-staff trade businesses in Canterbury. The campaign should start with 2 to 4 ad variants and a retargeting sequence, keep the human touch early, and avoid over-automating until the campaign proves lead quality.",
  },
];
